version: 0.0
os: linux
files:
  - source:  /
    destination: /var/www/html
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root

hooks:
  ApplicationStart:
    - location: scripts/after_deploy.sh
      timeout: 300
      runas: root
